services:
  dummy-service:
    image: "dummy-service:${IMAGE_VERSION}"
    container_name: "dummy-service"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8080/health').read()\" || exit 1"]
      interval: 10s
      retries: 3
      timeout: 3s
      start_period: 10s
    ports: 
      - "8000:8080"
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 256M
        reservations:
          cpus: 1
          memory: 128M
